FROM node:18-alpine AS base



FROM base as builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run flip-board:build
RUN npm run wingv:build



FROM base AS runner
WORKDIR /app
COPY --from=builder /app/dist/ ./
# install http-server to run Angular application
RUN npm install -g http-server
# expose 1314 port
EXPOSE 1314

# run Angular application
CMD ["http-server", "-p 1314", "./wingv"]
